# WRITE 3O METHODS IN NUMPY AND PANDAS WITH EXAMPLE

# GROUP 8
PARTICIPANTS
Rachael Henry 
Uchenna Okafor 
Olaitan Suru 
Jesu-Ebinimiedo Alagha 
Modupe Olumade 
Ooreoluwa Olusegun 
Freda Addo 
Hannah Atere 
Esther Adegbami


In [1]:
import numpy as np
import pandas as pd

# NUMPY

1. Arange - Return evenly spaced values within a gievn interval

In [3]:
np.arange(2,100)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

2. Zeros - Generate array of Zero

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Eye - Create an identity matrix

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

4. Ones - Generate array of Ones

In [6]:
np.ones(2)

array([1., 1.])

5. linspace - Return evenly spaced number over a specified interval

In [11]:
np.linspace(2,10,20)

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

6. Rand - Create an array of the given shape and population with random samples from a uniform distribution

In [4]:
np.random.rand(20)

array([0.25467715, 0.03665142, 0.64223691, 0.49868518, 0.26974424,
       0.57459024, 0.19078944, 0.84745292, 0.47885273, 0.15951983,
       0.24890746, 0.6828075 , 0.15883726, 0.3703464 , 0.88067221,
       0.69504129, 0.57308774, 0.67514572, 0.29796875, 0.5778668 ])

7. Reshape - Return an array containing the same data with a new shape 

In [12]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
arr.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

8. Shape - Shape is an attribute that an array have, Not a method

In [14]:
arr.shape

(30,)

9. Max - This returns the largest value from a list or array

In [16]:
arr.max()

29

10. Min - This returns the smallest value from a list or array

In [18]:
arr.min()

0

11. argmin - This returns the smallest value from the axis in a list or array

In [19]:
arr.argmin()

0

12. sum - This returns the sum of values in a list or array

In [25]:
arr.sum()

435

13. Array - Create an array

In [29]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

14. Indexing - Access elements by index

In [36]:
value=arr[7]
value

7

In [ ]:
15. Slicing - Extract a portion of an array

In [43]:
sliced_array=arr[1:3]
sliced_array

array([1, 2])

16. Mean - Average of array elements

In [44]:
np.mean(arr)

14.5

17. Transpose - Transpose of an array

In [47]:
Transposed_arr=arr.T
Transposed_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

18. Dot - Dot product of two arrays

In [54]:
arr2= np.arange(2,32)
arr2


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [55]:
np.dot(arr,arr2)

9425

19. Element-wise Operations - Addition, subtraction, multiplication, division

In [58]:
print(arr)
print(arr2)
elementwise_sum=(arr+arr2)
elementwise_sum

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

20. sqrt - Square root of array elements

In [59]:
np.sqrt(arr) 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])

21. log - Natural logarithm of array elements

In [60]:
np.log(arr) 

C:\Users\HP\AppData\Local\Temp\ipykernel_5556\1658632044.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583])

22. concatenate - Concatenate arrays along a given axis

In [78]:
np.concatenate((arr,arr2),axis=0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31])

23. unique - Unique values in an array

In [81]:
arr3= [1,3,2,1,4,1]
np.unique(arr3) 

array([1, 2, 3, 4])

24. corrcoef- Compute the correlation coefficient matrix

In [82]:
correlation_coefficient = np.corrcoef(arr,arr2)
correlation_coefficient


array([[1., 1.],
       [1., 1.]])

25. histogram - Compute histogram of data

In [83]:
hist, edges = np.histogram(arr, bins=5)
hist,edges

(array([6, 6, 6, 6, 6], dtype=int64),
 array([ 0. ,  5.8, 11.6, 17.4, 23.2, 29. ]))

26. random.randint - Generate random integers

In [86]:
rand_int_arr = np.random.randint(1, 10, size=(2, 3))
rand_int_arr


array([[9, 4, 4],
       [7, 5, 3]])

27. intersect1d - Find common elements between two arrays

In [87]:
np.intersect1d(arr,arr2)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

28. union1d- Find unique elements in both arrays

In [88]:
np.union1d(arr,arr2) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

29. isin - Check if elements of one array are present in another

In [89]:
np.isin(arr,arr2)

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

30. median- Calculate the median of an array

In [90]:
np.median(arr2) 

16.5

# PANDAS

1. DataFrame- Create a DataFrame

In [3]:
df = pd.DataFrame({'A': [10, 20, 30], 'B': ['w', 'x', 'y']})
df

A  B
0  10  w
1  20  x
2  30  y

2. tail - Display the last few rows of the DataFrame

In [110]:
df.tail(30)

A  B
0  10  w
1  20  x
2  30  y

3. to_csv() - Write DataFrame to a CSV file

In [33]:
df.to_csv('output.csv', index=False)
df.to_csv


<bound method NDFrame.to_csv of     A  B
0  20  A
1  40  B
2  60  C>

4. describe - Generate descriptive statistics of DataFrame

In [4]:
df_desc = df.describe()
df_desc 


A
count   3.0
mean   20.0
std    10.0
min    10.0
25%    15.0
50%    20.0
75%    25.0
max    30.0

5. info - Displays concise summary of DataFrame information

In [5]:
df.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   A       3 non-null      int64 
 1   B       3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes


6. shape - Get the dimensions of the DataFrame

In [6]:
df.shape

(3, 2)

7. dtypes - Get the data types of each column

In [114]:
df.dtypes


A     int64
B    object
dtype: object

8. loc - Access a group of rows and columns by labels or strings

In [115]:
subset = df.loc[1:2, ['A', 'B']]
subset

A  B
1  20  x
2  30  y

9. iloc - Access a group of rows and columns by integer index

In [119]:
subset = df.iloc[1:3,0:2]
subset

A  B
1  20  x
2  30  y

10. at - Access a single value using row and column labels

In [120]:
value = df.at[1, 'A']
value

20

11. iat - Access a single value using integer indices

In [121]:
value = df.iat[1, 0]
value

20

12. set_index - Set the DataFrame index

In [122]:
df.set_index('B')


A
B    
w  10
x  20
y  30

13. drop - Drops specified labels from rows or columns

In [123]:
df.drop(['A'], axis=1)


B
0  w
1  x
2  y

14. groupby - Group DataFrame by one or more columns

In [126]:
df.groupby('B').mean()


A
B      
w  10.0
x  20.0
y  30.0

15. dropna - Drops missing values from DataFrame

In [133]:
df = pd.DataFrame({"A":[1,np.nan,3,4,np.nan],
                  "B":[6,7,8,np.nan,np.nan],
                  "C":[np.nan,12,13,14,np.nan]})
print(df)
df.dropna()


     A    B     C
0  1.0  6.0   NaN
1  NaN  7.0  12.0
2  3.0  8.0  13.0
3  4.0  NaN  14.0
4  NaN  NaN   NaN


A    B     C
2  3.0  8.0  13.0

16. fillna - Fill missing values in DataFrame

In [135]:
df.fillna(2)

A    B     C
0  1.0  6.0   2.0
1  2.0  7.0  12.0
2  3.0  8.0  13.0
3  4.0  2.0  14.0
4  2.0  2.0   2.0

17. replace - Replace values in a DataFrame

In [8]:
df.replace({'A': {1: 'forty', 2: 'seventy'}})
 

A  B
0  10  w
1  20  x
2  30  y

18. to_excel - Write DataFrame to an Excel file

In [11]:
df.to_excel('output.xlsx', index=False)
df.to_excel


<bound method NDFrame.to_excel of     A  B
0  10  w
1  20  x
2  30  y>

19. map - Map values of Series according to input correspondence

In [15]:
df['B_mapped'] = df['B'].map({'a': 1, 'b': 2, 'c': 3})
df['B_mapped'] 


0   NaN
1   NaN
2   NaN
Name: B_mapped, dtype: float64

20. str.contains - Check if a string contains a specified substring

In [16]:
contains_substring = df['B'].str.contains('a')
contains_substring

0    False
1    False
2    False
Name: B, dtype: bool

21. pd.cut - Bin values into discrete intervals

In [18]:
bins = pd.cut(df['A'], bins=[0, 2, 4], labels=['group1', 'group2'])
bins 

0    NaN
1    NaN
2    NaN
Name: A, dtype: category
Categories (2, object): ['group1' < 'group2']

22. pd.qcut - Bin values into discrete quantiles

In [19]:
quantiles = pd.qcut(df['A'], q=[0, 0.5, 1], labels=['low', 'high'])
quantiles

0     low
1     low
2    high
Name: A, dtype: category
Categories (2, object): ['low' < 'high']

23. nunique - Count distinct observations in a DataFrame

In [20]:
unique_count = df.nunique()
unique_count

A           3
B           3
B_mapped    0
dtype: int64

24. pivot_table() - Create a pivot table

In [21]:
pivot_table = df.pivot_table(index='A', values='B', aggfunc='count')
pivot_table

B
A    
10  1
20  1
30  1

25. agg - Aggregate using one or more operations

In [22]:
aggregated_df = df.agg({'A': 'sum', 'B': 'count'})
aggregated_df

A    60
B     3
dtype: int64

26. groupby - Group DataFrame by one or more columns

In [24]:
grouped_df = df.groupby('B').mean()
grouped_df 

A  B_mapped
B                
w  10.0       NaN
x  20.0       NaN
y  30.0       NaN

27. sort_values - Sort DataFrame by one or more columns

In [26]:
df_sorted = df.sort_values(by='B', ascending=False)
df_sorted 

A  B  B_mapped
2  30  y       NaN
1  20  x       NaN
0  10  w       NaN

28. merge - Merge two DataFrames on a common column

In [28]:
df2 = pd.DataFrame({'A': [20, 40, 60], 'B': ['A', 'B', 'C']})
df2
df2.agg({'A': 'sum', 'B': 'count'})



A    120
B      3
dtype: int64

29. concat - Concatenate DataFrames along a particular axis

In [30]:
concatenated_df = pd.concat([df, df2], axis=0)
concatenated_df

A  B
0  20  A
1  40  B
2  60  C
0  20  A
1  40  B
2  60  C

30. drop_duplicates - Drop duplicated rows from a DataFrame

In [31]:
df_no_duplicates = df.drop_duplicates()
df_no_duplicates 

A  B
0  20  A
1  40  B
2  60  C